import streamlit as st
st.title('This is a title')
st.title('_Streamlit_ is :blue[cool] :happy:')
st.write("Hello")
name=st.text_input("Your name")
st.write("hello" + name)
col1, col2, col3 = st.columns(3)
col1.metric("Temperature", "18 C°", "1.5 C°")
col2.metric("Wind", "0 mph", "-8%")
col3.metric("Humidity", "10%", "4%")
